---

arch:
  - amd64
  - arm64

os: linux
dist: bionic

language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - apt install python3-pip

install:
  - pip install molecule docker

script:
  - molecule test
