---

arch:
  - amd64
  - arm64

os: linux

language: python
python:
  - "3.7"

services:
  - docker

before_install:
  - sudo apt install build-essential libssl-dev libffi-dev python3-dev

install:
  - pip install molecule docker

script:
  - molecule test
