---

arch:
  - amd64
  - arm64

os: linux
dist: bionic

language: python
python:
  - "3.6"

install:
  - pip search molecule
  - pip search docker
  - pip install molecule docker

script:
  - molecule test
